# -*- coding: utf-8 -*-
"""Big_data_management.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j__xCTzDSkOuqoPCr9y91hvd1b9-o4I6
"""

import pandas as pd
import numpy as np
from datetime import datetime, date

def remove_outliers(data, column):
  Q1 = np.percentile(data[column], 25,
                    interpolation = 'midpoint')
  
  Q3 = np.percentile(data[column], 75,
                    interpolation = 'midpoint')
  IQR = Q3 - Q1

  upper = np.where(data[column] >= (Q3+1.5*IQR))

  lower = np.where(data[column] <= (Q1-1.5*IQR))

  df_no_outliers = data.drop(upper[0], inplace = False)
  df_no_outliers.drop(lower[0], inplace = True)

  return df_no_outliers

#remove_outliers(df_unique,'Year_Birth') == remove_outliers(df_unique,'Age')

df_data = pd.read_csv('personality_analysis.csv', delimiter = ';')

#drop extra columns
df = df_data.iloc[:,0:27]

#drop duplicates (no duplicates exist)
df_unique = df.drop_duplicates()

#replace the missing Income values with the mean
mean = df_unique['Income'].mean()
df_unique['Income'] = df_unique['Income'].fillna(mean)
df_unique['Income'] = df_unique['Income'].astype(int)

#add age column
#df_unique['Age']= 2022 - df_unique['Year_Birth']

#remove outliers
df_no_outliers = remove_outliers(remove_outliers(df_unique,'Year_Birth'),'Income')

#convert Dt_Customer to date time obhect
df_no_outliers['Dt_Customer'] = pd.to_datetime(df_no_outliers['Dt_Customer'], dayfirst=True)



df.head(10)

df_no_outliers.head(10)

#df_no_outliers.to_csv('clean_data.csv',sep=',', header=False, index=False)